### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by linsui** [SIT-kite/kite-app#17]
**Is your feature request related to a problem? Please describe.**
可以在 F-Droid 上发布应用吗？

**Describe the solution you'd like**
我可以帮助打包

**Comment by sunnysab** [comment]
感谢。

由于项目最近处在交接过程中，我们希望等版本发布、特性更新的节奏稳定下来后再考虑上架到 F-Droid. 当前我们的 apk 是在服务器上存储并通过 CDN 分发的。
谢谢你对本项目的关注 :D

**Comment by linsui** [comment]
好的 :smile:
