### ISSUE TITLE
“课表” 自动跳转到非空白页面

### ISSUE THREAD

**Issue by sunnysab** [SIT-kite/kite-app#31]
rt. 
大一新生开学较晚，每次拖动太麻烦

**Comment by zhangzqs** [comment]
除了今年延期开学，以后估计很长一段时间都不会再发生这种事了

**Comment by liplum** [comment]
Now that the Timetable will jump to today as default, we don't need to worry about this.
At least, we have a good `Jump` button.

More:  Do we need to remeber the state such as which page users read last time? But users may prefer to jump directly to today's timetable.
