### ISSUE TITLE
统计用户设备信息

### ISSUE THREAD

**Issue by sunnysab** [SIT-kite/kite-app#33]
记录用户设备型号，以优化 UI. @liplum 

要实现此功能，可以在客户端报告 `首次使用` 消息时，同时上报客户端设备信息、版本。

**Comment by liplum** [comment]
### Device Info
The device info, including operation system, device model/brand and screen size on deskop (maybe), should be reported if there is no records in database about the first installation time.
### Version Info
Every request should include the version info for server to judge revision, legacy supports and statistics.
