### ISSUE TITLE
Renaming and Standardization

### ISSUE THREAD

**Issue by liplum** [SIT-kite/kite-app#47]
# Proposal
We need to rename almost all things that have been partially talking about in those [documents](https://github.com/SIT-kite/kite-app/tree/master/specifications).

# Purpose
1. The old names in English often mislead developers and are even misused.
2. To reduce ambiguity and burden of maintaining two different things but with the same name, which are not distinguished properly somewhere.

# Progress
Check the pull request to obtain more inforamtion about the progress: https://github.com/SIT-kite/kite-app/pull/48.

**Comment by liplum** [comment]
`KvStorageInitializer` in [init.dart](https://github.com/SIT-kite/kite-app/blob/master/lib/storage/init.dart) is a name that terribly describes its function and is too long for the access of static field.
I think class `Kv`, which holds the static fields, and class `KvInit`, which works for initializing the `Kv`, would be better

**Comment by liplum** [comment]
The [*Term of Kite*](https://github.com/SIT-kite/kite-app/blob/master/specifications/TERM.md) has summarized the new name of all `FunctionType`, btw, maye `FunctionType` will be renamed later.

**Comment by liplum** [comment]
Comes with the renaming, another trouble that the back-end server should make change simultaneously sets up obstacles to modify the route name, which has worked for a long while on the older version.
To sum up, changing the route name is a breaking change but it worth discussing.

**Comment by sunnysab** [comment]
It costs many to do some renaming back-end server. You should not want to change if it's really necessary.

For compatability.

**Comment by liplum** [comment]
> It costs many to do some renaming back-end server. You should not want to change if it's really necessary. 
> For compatability.

So we can make a table, in the [sepcifications](https://github.com/SIT-kite/kite-app/tree/master/specifications), to map the front-end to back-end for old version compatability without any real change applied on back-end.

And we can collect users' Kite version, not sensitive against *Kite's privacy policy*, for statistics use in order to assess how much impact renaming back-end will have. Then we can safely do the job.

Edited: [Here](https://github.com/SIT-kite/kite-app/blob/rename/specifications/TERM.md) is the old name mapping.

**Comment by liplum** [comment]
All jobs are done. Now it's the time to review and prepare for merging.
