### ISSUE TITLE
2022易班新生群封禁

### ISSUE THREAD

**Issue by ChlorophyTeio** [SIT-kite/kite-app#57]
求一个后备群@sunnysab

**Comment by ChlorophyTeio** [comment]
@sunnysab

**Comment by sunnysab** [comment]
这个锅得 github 背一点，因为我没收到邮件提醒……
他们后来改成钉钉群了，我没加，似乎也没有多少人加 🤔具体情况不是很清楚，如果你需要二维码的话，再 reply 一下，谢谢！
