### ISSUE TITLE
Clear cache button in settings.

### ISSUE THREAD

**Issue by liplum** [SIT-kite/kite-app#66]
If the cache takes too much room, users may be willing to delete them.
To add a `Clear Cache` button sounds good.
In some edge cases, clearing cache let the UI fetch the latest data immediately, which will solve some issues that have not been considered so far.

**Comment by sunnysab** [comment]
用一两个月看看 Cache 有多大，甚至可以上报用户存储大小 :D

**Comment by liplum** [comment]
It's an opportunity to trace the cache, but my point is still here, adding a `Clear Cache` button.

**Comment by liplum** [comment]
But how can we get/calculate the size of cache with hive?
